version: '3'
services:
  dev:
    build: .
    ports:
      - '8080:80'
  prod:
    build: .
    restart: on-failure
    network_mode: bridge
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '10'
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: .joris.me
      HTTPS_METHOD: nohttps